### ISSUE TITLE
Wrong rule name: s/@lh/@hack

### ISSUE THREAD

**Issue by Metalaka** [hoaproject/Dispatcher#19]
Hi, as you can see on [hoa-project.net/Fr/Literature/Hack/Dispatcher](http://hoa-project.net/Fr/Literature/Hack/Dispatcher.html) there is a little error :)

Error: `...règle (voir string(23) "Rule lh does not exist."`

Source: [Documentation/Fr/Index.xyl#L24](https://github.com/hoaproject/Dispatcher/blob/master/Documentation/Fr/Index.xyl#L24)
`...règle (voir <a href="@lh:chapter=Router">la bibliothèque
  <code>Hoa\Router</code></a> si...`

As we can see on [`Hoa\Router` doc](https://github.com/hoaproject/Router/blob/master/Documentation/Fr/Index.xyl#L810) the rule name should be `hack`.
See [`s/@lh/@hack` commit](https://github.com/hoaproject/Router/commit/f1ade22ca0af0c6cbf5325bbac4d65a6eb752a5d) in `Hoa\Router`.

I didn't do a PR because I can't test whether it's just that or not ;)

**Comment by Hywan** [comment]
Fixed by https://github.com/hoaproject/Dispatcher/commit/a65fab88e491d1bfe989bfdf7771509940c8cdcf. Thanks! This documentation is not released yet because there is few issues to close. Help would be welcome on these issues ;-)!
