### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by camael24** [hoaproject/Dispatcher#21]
Hey,

I have a Fatal Error : PHP Fatal error:  Cannot mix bracketed namespace declarations with unbracketed namespace declarations in C:\www\sohapi\vendor\hoa\console\Dispatcher\Kit.php on line 37
I think its come from the Core , who still have file with namespace {} and namespace ;
I try to fix it, but when we declare namespace foo; we can't return on the global namespace namespace ;

And if we force tu use namespace Hoa\Core; all function defined on root can't be access ie ( dnew => \Hoa\Core\Consistence\dnew() )... i don't have any solution for it

**Comment by Hywan** [comment]
What are you trying to achieve?

**Comment by camael24** [comment]
I Just want to use the hoa binairies `$ hoa`

**Comment by Hywan** [comment]
It works here. What versions of what libraries do you have?

**Comment by camael24** [comment]
I don't know how translate it : 
Je me suis planté dans mon explication c'était pas en utilsant la commande Hoa mais la commande Sohapi, en investiguant plus en profondeur j'ai changer les namespace { en namespace ; et magie tout marche niquel, donc encore une fois c'est un bug chaise-clavier, c'est juste que la Fatal Error est vraiment mal nommé ... merci php :+1: 
Je clos l'issue

**Comment by Hywan** [comment]
The error was not located in Hoa but in another program.
